export { ChromeIcon } from './Chrome'
export { BrowserIcon } from './Browser'
export { DesctopIcon } from './Desctop'
export { FireFoxIcon } from './FireFox'
export { OperaIcon } from './Opera'
export { YandexIcon } from './Yandex'
export { MobileIcon } from './Mobile'
