export const PATH = {
  HOME: '/',
  CREATE: 'create',
  MY_PROFILE: 'my-profile',
  MESSENGER: 'messenger',
  SEARCH: 'search',
  STATISTIC: 'statistics',
  SIGN_UP: '/auth/sign-up',
  SIGN_IN: '/auth/sign-in',
  FAVORITES: 'favorites',
  FORGOT_PASSWORD: '/auth/forgot-password',
  LOGOUT: 'logout',
  POLICY: '/auth/privacy-policy',
  TERMS_OF_SERVICE: '/auth/terms-of-service',
}
