export const PATH = {
  HOME: '/',
  CREATE: '/create',
  MY_PROFILE: '/profile',
  MY_PROFILE_SETTINGS: '/profile/settings',
  MY_PROFILE_SETTINGS_GENERAL: '/profile/settings/general',
  MY_PROFILE_SETTINGS_DEVICES: '/profile/settings/devices',
  MY_PROFILE_SETTINGS_ACCOUNT_MANAGEMENT: '/profile/settings/account-management',
  MESSENGER: '/messenger',
  SEARCH: '/search',
  STATISTIC: '/statistics',
  SIGN_UP: '/auth/sign-up',
  SIGN_IN: '/auth/sign-in',
  FAVORITES: '/favorites',
  FORGOT_PASSWORD: '/auth/forgot-password',
  LOGOUT: '/logout',
  POLICY: '/auth/privacy-policy',
  TERMS_OF_SERVICE: '/auth/terms-of-service',
  USER: '/user',
}
